#!/bin/bash
set -e

echo "========================================="
echo "  OpenVPN Server Starting..."
echo "========================================="

# Environment variables with defaults
OPENVPN_NETWORK=${OPENVPN_NETWORK:-10.8.0.0}
OPENVPN_NETMASK=${OPENVPN_NETMASK:-255.255.255.0}
OPENVPN_DNS_1=${OPENVPN_DNS_1:-8.8.8.8}
OPENVPN_DNS_2=${OPENVPN_DNS_2:-1.1.1.1}

# Backend-managed subnet override: when an admin changes the VPN network from the
# panel, the backend writes this file to the shared /etc/openvpn volume. It takes
# precedence over the compose env so the subnet can change on a plain container
# restart (no recreate needed).
if [ -f /etc/openvpn/network.env ]; then
    . /etc/openvpn/network.env
fi

# Derive the CIDR prefix from the dotted netmask (for MASQUERADE / routing).
netmask_to_cidr() {
    local mask=$1 bits=0 octet
    local IFS=.
    for octet in $mask; do
        case $octet in
            255) bits=$((bits+8));; 254) bits=$((bits+7));; 252) bits=$((bits+6));;
            248) bits=$((bits+5));; 240) bits=$((bits+4));; 224) bits=$((bits+3));;
            192) bits=$((bits+2));; 128) bits=$((bits+1));; 0) ;; *) echo 24; return;;
        esac
    done
    echo $bits
}
OPENVPN_CIDR=$(netmask_to_cidr "${OPENVPN_NETMASK}")

# Network interface (single interface mode)
PUBLIC_INTERFACE=${PUBLIC_INTERFACE:-eth0}

# Setup directories on volume
mkdir -p /etc/openvpn/{ccd,logs,pki,scripts}

# Refresh scripts from image to volume on every start.
# These are CODE, not data — always overwrite so updates actually take effect.
# (The old "copy only if missing" guard silently froze scripts across updates.)
# Certs/PKI/ccd/server.conf are data and are handled separately below, never here.
echo "Refreshing OpenVPN scripts from image..."
cp /opt/openvpn-scripts/*.sh /etc/openvpn/scripts/ 2>/dev/null || true
chmod +x /etc/openvpn/scripts/*.sh 2>/dev/null || true

# Setup EasyRSA on volume
if [ ! -d "/etc/openvpn/easy-rsa" ]; then
    echo "Setting up EasyRSA..."
    cp -r /usr/share/easy-rsa /etc/openvpn/easy-rsa
    chmod +x /etc/openvpn/easy-rsa/easyrsa
fi

# Create required directories
mkdir -p /etc/openvpn/{ccd,logs,pki,firewall}
chmod 777 /etc/openvpn/ccd  # Allow backend to write CCD files
chmod 777 /etc/openvpn/logs  # Allow nobody user to write logs

# Create log files with proper permissions (OpenVPN runs as nobody)
touch /etc/openvpn/logs/openvpn.log
touch /etc/openvpn/logs/status.log
touch /etc/openvpn/logs/auth.log
chmod 666 /etc/openvpn/logs/*.log

# Initialize PKI if not exists (check for all required files)
if [ ! -f "/etc/openvpn/ca.crt" ] || [ ! -f "/etc/openvpn/ta.key" ] || [ ! -f "/etc/openvpn/server.crt" ]; then
    echo "Initializing PKI..."
    cd /etc/openvpn/easy-rsa

    # Set vars for non-interactive mode
    export EASYRSA_BATCH=1
    export EASYRSA_REQ_CN="VPN-CA"
    export EASYRSA_PKI=/etc/openvpn/easy-rsa/pki

    # Initialize PKI
    ./easyrsa init-pki

    # Build CA (non-interactive)
    ./easyrsa --batch build-ca nopass

    # Generate DH
    echo "Generating DH parameters (this may take a while)..."
    ./easyrsa --batch gen-dh

    # Generate server cert - use gen-req + sign-req instead of build-server-full
    echo "Generating server certificate..."
    ./easyrsa --batch gen-req server nopass
    ./easyrsa --batch sign-req server server

    # Generate TLS key
    echo "Generating TLS key..."
    openvpn --genkey secret /etc/openvpn/ta.key

    # Copy files to openvpn directory
    cp pki/ca.crt /etc/openvpn/
    cp pki/dh.pem /etc/openvpn/
    cp pki/issued/server.crt /etc/openvpn/
    cp pki/private/server.key /etc/openvpn/

    # Set permissions so backend (running as uid 1000) can access and write to PKI
    chmod -R 777 /etc/openvpn/easy-rsa/pki
    chmod 644 /etc/openvpn/ta.key /etc/openvpn/ca.crt

    echo "PKI initialized successfully"
else
    echo "PKI already exists, skipping initialization"
fi

# Return to OpenVPN directory
cd /etc/openvpn

# Verify all required files exist
for file in ca.crt server.crt server.key dh.pem ta.key; do
    if [ ! -f "/etc/openvpn/$file" ]; then
        echo "ERROR: Missing required file: /etc/openvpn/$file"
        exit 1
    fi
done
echo "All required files verified"

# Generate server config if not exists
if [ ! -f "/etc/openvpn/server.conf" ]; then
    echo "Generating server configuration..."

    cat > /etc/openvpn/server.conf << EOF
# OpenVPN Server Configuration
# Generated by VPN Management System

port 1194
proto udp
dev tun

# Certificates
ca ca.crt
cert server.crt
key server.key
dh dh.pem
tls-auth ta.key 0

# Network
server ${OPENVPN_NETWORK} ${OPENVPN_NETMASK}
topology subnet

# Push routes to clients
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS ${OPENVPN_DNS_1}"
push "dhcp-option DNS ${OPENVPN_DNS_2}"

# Client config directory
client-config-dir ccd

# Persist IP assignments
ifconfig-pool-persist ipp.txt

# Keepalive
keepalive 10 120

# Anti-queda na renegociacao TLS de 1h (redes/dispositivos instaveis)
# reneg-sec 0 desliga a renegociacao por tempo, que falhava e derrubava a sessao em ~1h.
# As chaves ainda rotacionam a cada reconexao. Trade-off aceitavel com AES-256-GCM.
# NAO usar tun-mtu/push tun-mtu: quebra o canal de dados (tunel sobe mas nada e encaminhado).
mssfix 1360
explicit-exit-notify 1
reneg-sec 0
push "reneg-sec 0"

# Encryption
cipher AES-256-GCM
auth SHA256
tls-version-min 1.2

# Privileges
user nobody
group nogroup
persist-key
persist-tun

# Logging
status logs/status.log 10
log-append logs/openvpn.log
verb 3
mute 20

# Management interface for backend
management 0.0.0.0 7505

# Client authentication via backend
auth-user-pass-verify /etc/openvpn/scripts/auth.sh via-env
script-security 3
username-as-common-name

# Allow clients without certificates (auth via password)
verify-client-cert optional

# Connection scripts
client-connect /etc/openvpn/scripts/client-connect.sh
client-disconnect /etc/openvpn/scripts/client-disconnect.sh
EOF

    echo "Server configuration created"
fi

# Setup NAT/Routing with Firewall
echo "Configuring Firewall and NAT..."

# IP forwarding is enabled via sysctl in docker-compose.yml

# Create firewall rules directory
mkdir -p /etc/openvpn/firewall
touch /etc/openvpn/firewall/allowed_networks.conf
# Default: block client-to-client (remove flag if exists from previous run)
rm -f /etc/openvpn/firewall/client_to_client_enabled

# Flush existing rules
iptables -F FORWARD 2>/dev/null || true
iptables -F VPN_FILTER 2>/dev/null || true
iptables -X VPN_FILTER 2>/dev/null || true

# Create VPN_FILTER chain
echo "  Creating VPN_FILTER chain..."
iptables -N VPN_FILTER 2>/dev/null || true

# === VPN_FILTER Chain Rules ===
# ORDEM CORRETA: Exceções primeiro, depois DROP, depois ACCEPT

# 1. Permitir redes internas configuradas (exceções ao bloqueio)
if [ -f /etc/openvpn/firewall/allowed_networks.conf ]; then
    while IFS= read -r network || [ -n "$network" ]; do
        # Skip empty lines and comments
        [[ -z "$network" || "$network" =~ ^# ]] && continue
        echo "  Allowing internal network: $network"
        iptables -A VPN_FILTER -d "$network" -j ACCEPT
    done < /etc/openvpn/firewall/allowed_networks.conf
fi

# 2. Bloquear todas as redes privadas (RFC1918)
echo "  Blocking private networks by default..."
iptables -A VPN_FILTER -d 10.0.0.0/8 -j DROP
iptables -A VPN_FILTER -d 172.16.0.0/12 -j DROP
iptables -A VPN_FILTER -d 192.168.0.0/16 -j DROP

# 3. Permitir serviços para internet (destinos públicos)
iptables -A VPN_FILTER -p icmp -j ACCEPT
iptables -A VPN_FILTER -p udp --dport 53 -j ACCEPT
iptables -A VPN_FILTER -p tcp --dport 80 -j ACCEPT
iptables -A VPN_FILTER -p tcp --dport 443 -j ACCEPT

# 4. Permitir todo o resto (internet)
iptables -A VPN_FILTER -j ACCEPT

# === FORWARD Chain ===
echo "  Setting up FORWARD chain..."
# Set default policy to DROP
iptables -P FORWARD DROP

# Allow return traffic
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

# VPN traffic goes through VPN_FILTER
iptables -A FORWARD -i tun0 -o ${PUBLIC_INTERFACE} -j VPN_FILTER

# Allow return traffic from interface to VPN
iptables -A FORWARD -i ${PUBLIC_INTERFACE} -o tun0 -m state --state ESTABLISHED,RELATED -j ACCEPT

# === NAT (MASQUERADE) ===
echo "  Setting up MASQUERADE for ${PUBLIC_INTERFACE}..."
iptables -t nat -F POSTROUTING 2>/dev/null || true
iptables -t nat -A POSTROUTING -s ${OPENVPN_NETWORK}/${OPENVPN_CIDR} -o ${PUBLIC_INTERFACE} -j MASQUERADE

echo "Firewall and NAT configuration complete."
echo "  - Private networks BLOCKED by default"
echo "  - Client-to-client BLOCKED by default"
echo "  - Use /etc/openvpn/firewall/allowed_networks.conf to allow specific networks"

# Change to OpenVPN directory (important for relative paths in config)
cd /etc/openvpn

# Verify files exist before starting
echo "Verifying files in $(pwd):"
ls -la ca.crt server.crt server.key dh.pem ta.key 2>/dev/null || echo "WARNING: Some files missing!"
ls -la logs/ 2>/dev/null || echo "WARNING: logs directory missing!"

echo "========================================="
echo "  OpenVPN Server Ready"
echo "  Network: ${OPENVPN_NETWORK}/${OPENVPN_NETMASK}"
echo "  Port: 1194/UDP"
echo "========================================="

# Start OpenVPN from /etc/openvpn directory
exec openvpn --cd /etc/openvpn --config server.conf
